databases:
  - name: postgres
    ipAllowList: [] # only allow internal connections

services:
  - type: web
    name: rails
    env: ruby
    repo: https://github.com/Mortle/tickets-manager
    buildCommand: bundle install && bundle exec rails assets:precompile && bundle exec rails db:migrate
    startCommand: bundle exec rails s
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
